//import flowbitePlugin from "flowbite/plugin";

import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/flowbite-react/**/*.{js,jsx,ts,tsx}",
  ],
  plugins: [require('flowbite/plugin')],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          "50": "#eff6ff",
          "100": "#dbeafe",
          "200": "#bfdbfe",
          "300": "#93c5fd",
          "400": "#60a5fa",
          "500": "#3b82f6",
          "600": "#2563eb",
          "700": "#1d4ed8",
          "800": "#1e40af",
          "900": "#1e3a8a",
          "950": "#172554",
        },
        "cetera-orange": "#f85f14",
        "cetera-blue": "#1087ff",
        "cetera-gray": "#1F2937",
        "cetera-peach": "#F4A77A",
        "cetera-mono-orange": "#F27830",
        "cetera-dark-orange": "#BF5E26",
        "cetera-bright-orange": "#F56E4E",
        "cetera-hot-orange": "#F24405",
        "cetera-hot-pink": "#F5514E",
        "cetera-light-pink": "#F2DDD5",
        "cetera-cute-orange": "#F58B4E",
        "cetera-mono-yellow": "#F5BF4E",
        "cetera-dark-yellow": "#F5A94E",
        "cetera-taupe": "#D9896C",
        "cetera-mono-brown": "#BF6550",
        "cetera-light-gray": "#F4F2F0",
        "cetera-dark-blue": "#273B5B",
        "cetera-mono-blue": "#36649A",
        "cetera-light-blue": "#6B9BBC",
        "dark-blue": "#111827",
        "regal-blue": "#243c5a",
        "light-blue": "#a9d4ff",
        "light-gray": "#f7f7f7",
      },
    },
    variants: {
      extend: {
        textColor: ["active"], // Enable active variant
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
        "Libre Baskerville",
        "Jost",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      "cetera-libre":  "Libre Baskerville",
      "cetera-jost":  "Jost",
      "cetera-josefin": "Josefin Sans",
      "cetera-bungee": "Bungee Hairline",
    },
    height: {
      "45vh": "45vh",
      "46vh": "46vh",
      "536vh": "53.6vh",
    },
  },
};
export default config;
