import type { Metadata } from "next";
//import { Inter } from "next/font";
import { ThemeModeScript } from "flowbite-react";
import PageWrapper from "@/components/animations/page-wrapper.js";
import CustomNav from "@/components/page-sections/navbar.js";
import Footer from "@/components/page-sections/footer.js";
import { Providers } from "./providers.tsx";
import "./globals.css";

/*const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});*/


export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-sans antialiased">
        <Providers>
          <CustomNav />
          <PageWrapper>{children}</PageWrapper>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
