//app/layout.tsx
import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import PageWrapper from "@/components/animations/page-wrapper.js";
import CustomNav from "@/components/page-sections/navbar.js";
import Footer from "@/components/page-sections/footer.js";
import { Providers } from "./providers.tsx";
import { OrderProvider } from "@/context/OrderContext.js";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Bungee+Hairline&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Jost:ital,wght@0,100..900;1,100..900&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap"
            rel="stylesheet"
          />
        {/* Preconnect to improve font loading */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body 
        className="font-sans antialiased bg-cetera-light-gray"
        suppressHydrationWarning
      >
        <OrderProvider>
          <Providers>
            <CustomNav />
            <PageWrapper>{children}</PageWrapper>
            <Footer />
          </Providers>
        </OrderProvider>
      </body>
    </html>
  );
}